'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class EmailTrigger2014

    '''<summary>
    '''btnFabricCuttingYarnMail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFabricCuttingYarnMail As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''btnNeworRepeatOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNeworRepeatOrder As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''btnInspection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnInspection As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''btnNoCertificate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNoCertificate As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''btnVAF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnVAF As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''btnInspectionRoster control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnInspectionRoster As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''btnWeeklySamplingPass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnWeeklySamplingPass As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''btnWeeklySamplingFail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnWeeklySamplingFail As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''btnCuttingApproval control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCuttingApproval As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''btninlineinspection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btninlineinspection As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''btn2inlineinspection control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btn2inlineinspection As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''btnFinalInspectionPlanning control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFinalInspectionPlanning As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''btnokaytoship control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnokaytoship As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''btnCloseOrders control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCloseOrders As Global.Telerik.Web.UI.RadButton

    '''<summary>
    '''dgOpenOrder control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgOpenOrder As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''dgInspectionAlert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgInspectionAlert As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''dgInspectionRoster control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgInspectionRoster As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''dgWeeklySamplingPass control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgWeeklySamplingPass As Global.System.Web.UI.WebControls.GridView

    '''<summary>
    '''dgCuttingApproved control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgCuttingApproved As Global.System.Web.UI.WebControls.GridView
End Class
