'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class OfferDevSampleRecvFromSupplier

    '''<summary>
    '''UpcmbCustomer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpcmbCustomer As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''cmbCustomer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbCustomer As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''UpcmbBuyingDept control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpcmbBuyingDept As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''cmbBuyingDept control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbBuyingDept As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''UpdatecmbBuyerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatecmbBuyerName As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''cmbBuyerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbBuyerName As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''UpcmbBrand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpcmbBrand As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''cmbBrand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbBrand As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''UpcmbSeason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpcmbSeason As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''cmbSeason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbSeason As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''UpStyleNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpStyleNo As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''cmbStyle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbStyle As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtstyle control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtstyle As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''UptxtStyleDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UptxtStyleDescription As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtStyleDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStyleDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''UpDesignName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpDesignName As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtDesignName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDesignName As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''UpSupplier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpSupplier As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''cmbsupplier control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbsupplier As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''UpcmbSample control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpcmbSample As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''cmbSample control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbSample As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Upadd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Upadd As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnAddSample control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddSample As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnAddMoreSample control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddMoreSample As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''UpUpbtndgSampleDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpUpbtndgSampleDetail As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''dgSampleDetail control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgSampleDetail As Global.SmartControls.Controls.SmartDataGrid

    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button
End Class
