'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class ShipmentFormEntry

    '''<summary>
    '''cmbInvoiceNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbInvoiceNo As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtBLorAWB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBLorAWB As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rdpDiscrepacyMsgDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdpDiscrepacyMsgDate As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''txtBuyer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBuyer As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rdpBLorAWBDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdpBLorAWBDate As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''rdpTelexSendingDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdpTelexSendingDate As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''txtCurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCurrency As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtContainerNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtContainerNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rdpPayMaburityDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdpPayMaburityDate As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''txtInvoiceAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInvoiceAmount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtContainerSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtContainerSize As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAmountToBeRealized control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAmountToBeRealized As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rdpInvoiceDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdpInvoiceDate As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''rdpETADestination control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdpETADestination As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''txtExchangeRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExchangeRate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtExFactoryDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExFactoryDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtClearingAgent control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtClearingAgent As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAmountInPKR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAmountInPKR As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtQtyPcs control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQtyPcs As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtGD control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGD As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPurchaseAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPurchaseAmount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtLCNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtLCNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rdpGDDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdpGDDate As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''txtPurchaseRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPurchaseRate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rdpLCDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdpLCDate As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''TXTPaymentTerms control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TXTPaymentTerms As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPurchaseAmountPKR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPurchaseAmountPKR As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cmbShipMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbShipMode As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtPaymentDays control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPaymentDays As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rdpPurchaseDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdpPurchaseDate As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''cmbShipTerm control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbShipTerm As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''rdpDocsSubmitIntoBankOn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdpDocsSubmitIntoBankOn As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''txtBalRealizedAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBalRealizedAmount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBankCode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBankCode As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtBankToBankDHLNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBankToBankDHLNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtRealizedRate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRealizedRate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtFormENo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFormENo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rdpBankToBankDHLDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdpBankToBankDHLDate As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''txtBalRealizedAmountPKR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBalRealizedAmountPKR As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rdpFormEDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdpFormEDate As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''txtBuyerDHLNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBuyerDHLNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''rdpRealizedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdpRealizedDate As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''rdpBuyerDHLDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rdpBuyerDHLDate As Global.Telerik.Web.UI.RadDatePicker

    '''<summary>
    '''txtFBCharges control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtFBCharges As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtExpectedPayRecDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtExpectedPayRecDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtNetRealizedAmount control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNetRealizedAmount As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtNetRealizedAmountPKR control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtNetRealizedAmountPKR As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtRemarks control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRemarks As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cbPaymentReceived control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cbPaymentReceived As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button
End Class
