'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class StyleDatabaseEntry

    '''<summary>
    '''txtCreatedBy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCreatedBy As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCreatedOn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCreatedOn As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''UpdatePanel8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel8 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''rbnSelect control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbnSelect As Global.System.Web.UI.WebControls.RadioButtonList

    '''<summary>
    '''UpStyleNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpStyleNo As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtStyleNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStyleNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cmbStyleNoo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbStyleNoo As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''UpCoreLine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpCoreLine As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtCoreLine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCoreLine As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cmbSpecialLine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbSpecialLine As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''UpcmbCustomer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpcmbCustomer As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''cmbCustomer control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbCustomer As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''UptxtStyleDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UptxtStyleDescription As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtStyleDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtStyleDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''UpcmbSeason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpcmbSeason As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''cmbSeason control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbSeason As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''UpdatePanel3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel3 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''cmbStyleSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbStyleSource As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''UpcmbBuyingDept control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpcmbBuyingDept As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''cmbBuyingDept control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbBuyingDept As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''UpdatecmbBuyerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatecmbBuyerName As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''cmbBuyerName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbBuyerName As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''UpcmbBrand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpcmbBrand As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''cmbBrand control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbBrand As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''UpFabFinish control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpFabFinish As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''UpcmbProductPortfolio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpcmbProductPortfolio As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''cmbProductPortfolio control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbProductPortfolio As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''UpcmbProductCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpcmbProductCategory As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''cmbProductCategory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbProductCategory As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''UpdatePanel12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel12 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''cmbProductConsumerGrp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbProductConsumerGrp As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''UpLining control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpLining As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''cmbLining control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbLining As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Uplblpack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Uplblpack As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblpack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblpack As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanel6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel6 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''cmbPack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbPack As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Upadd control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Upadd As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnAddProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddProduct As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnAddMoreProduct control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddMoreProduct As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''UpUpbtnAutoComplete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpUpbtnAutoComplete As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''dgProductinfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgProductinfo As Global.SmartControls.Controls.SmartDataGrid

    '''<summary>
    '''UpbtnAutoComplete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpbtnAutoComplete As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnAutoComplete control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAutoComplete As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''UpdatePanel9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel9 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtColorRefNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtColorRefNo As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtColorway control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtColorway As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''UpcmbSizeRange control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpcmbSizeRange As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''cmbSizeRange control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbSizeRange As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''Uplblitem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Uplblitem As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''lblitem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblitem As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpcmbBaseItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpcmbBaseItem As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''cmbBaseItem control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbBaseItem As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtPrice control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPrice As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cmbCurrency control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbCurrency As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''btnAddColor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddColor As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnHide control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnHide As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnShow control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnShow As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''PnlColor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PnlColor As Global.System.Web.UI.WebControls.Panel

    '''<summary>
    '''dgColor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgColor As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''UpcmbAccessories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpcmbAccessories As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''cmbAccessories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbAccessories As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''UptxtAccessoriesDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UptxtAccessoriesDescription As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''txtAccessoriesDescription control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAccessoriesDescription As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''UpcmbSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpcmbSource As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''cmbSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbSource As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''upbtnAddAccessories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upbtnAddAccessories As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''btnAddAccessories control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddAccessories As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''Updgacss control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Updgacss As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''dgAcces control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgAcces As Global.Telerik.Web.UI.RadGrid

    '''<summary>
    '''UpcmbEmbell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpcmbEmbell As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''cmbEmbell control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbEmbell As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtAcceptableDimensionalL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAcceptableDimensionalL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtAcceptableDimensionalW control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtAcceptableDimensionalW As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtRubbingFastnessWet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRubbingFastnessWet As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtRubbingFastnessDry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRubbingFastnessDry As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''cmbTypeOfDyes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbTypeOfDyes As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cmbTypeOfPrint control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbTypeOfPrint As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cmbTypeOfWashing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbTypeOfWashing As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cmbdegree1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbdegree1 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cmbdegree2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbdegree2 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cmbdegree3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbdegree3 As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cmbBleachingSymbol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbBleachingSymbol As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cmbIroningSymbol control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbIroningSymbol As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cmbDryCleaning control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbDryCleaning As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cmbTumbleDry control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbTumbleDry As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtBuyerTechComment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBuyerTechComment As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCartonType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCartonType As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCartonSizeL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCartonSizeL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCartonSizeW control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCartonSizeW As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtCartonSizeH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCartonSizeH As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''UpdatePanel1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel1 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''cmbCartonSizeUnitID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbCartonSizeUnitID As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtQtyCarton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQtyCarton As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''UpdcmbQtyCartonUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdcmbQtyCartonUnit As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''cmbQtyCartonUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbQtyCartonUnit As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtQtyPack control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQtyPack As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''UpdatePanel7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel7 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''cmbQtyPackUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbQtyPackUnit As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtPolyBagSizeL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPolyBagSizeL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPolyBagSizeW control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPolyBagSizeW As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPolyBagSizeFlap control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPolyBagSizeFlap As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''UpdatePanel2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel2 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''cmbPolyBagSizeUnitID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbPolyBagSizeUnitID As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtInlayCardSize control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInlayCardSize As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPackedPcSzL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPackedPcSzL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPackedPcSzW control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPackedPcSzW As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''UpdatePanel4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel4 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''cmbPackedPcUnitID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbPackedPcUnitID As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtGrossWeightofCarton control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGrossWeightofCarton As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''UpdcmbGrossWeightCartonUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdcmbGrossWeightCartonUnit As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''cmbGrossWeightCartonUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbGrossWeightCartonUnit As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''txtPolyBagStickerSizeL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPolyBagStickerSizeL As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtPolyBagStickerSizeW control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPolyBagStickerSizeW As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblH As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPolyBagStickerSizeH control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPolyBagStickerSizeH As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblUnit As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdatePanel5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel5 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''cmbPolyBagStickerSizeUnitID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbPolyBagStickerSizeUnitID As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''imgExtra control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents imgExtra As Global.System.Web.UI.WebControls.Image

    '''<summary>
    '''txtInsetComplainttype control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtInsetComplainttype As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''UpdatePanel10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdatePanel10 As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''cmbFileType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbFileType As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''FileUpload1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents FileUpload1 As Global.System.Web.UI.WebControls.FileUpload

    '''<summary>
    '''btnUpload1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnUpload1 As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblErrorMsg control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblErrorMsg As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''UpdgFileInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents UpdgFileInfo As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''dgFileInfo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents dgFileInfo As Global.SmartControls.Controls.SmartDataGrid

    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button
End Class
