'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class StyleInspectionReport

    '''<summary>
    '''txtPONO control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPONO As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblpoid control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblpoid As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''autoComplete1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents autoComplete1 As Global.AjaxControlToolkit.AutoCompleteExtender

    '''<summary>
    '''cmbPONo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbPONo As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''cmbColor control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cmbColor As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''lblStyleID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStyleID As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''btnSreach control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSreach As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnFabric control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFabric As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnFabricIns control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnFabricIns As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnPacking control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPacking As Global.System.Web.UI.WebControls.Button
End Class
